### ISSUE TITLE
小车的控制方案是什么？ 

### ISSUE THREAD

**Issue by helxsz** [GNSS523/ai_car_embedded#2]
你们有几种小车的控制方案？用什么器件， PI ， nodemcu ， 超声波传感，NK1 板子 ， 还有没有其他什么？

**Comment by helxsz** [comment]
简答说下方案

方案 1  控制板  <-  IO口 -> 马达驱动板
方案 2  控制板  <-  IO口 ->  microcontroller板 <- IO口-> 马达驱动板组成
方案 3  控制板  <- 蓝牙 ->  microcontroller板 <- IO口-> 马达驱动板组成
方案 4  控制板  <- WIFI -> 服务器  <- WIFI -> microcontroller板 <- IO口-> 马达驱动板组成

方案1，2都是通过IO口相对直连
方案3，4都是有延时，当然方案4的延时可能最多，可靠性不够。
1. 控制层/控制板，可以用 PI 或者 NK1. 

硬件层面上，PI 和 NK1 是类似的， PI可以加载PI camera采集视频； NK1 同样可以加载摄像头(USB摄像头或者 3D摄像头 realsense)，只不过NK1更加powerful，有192核的GPU。

通信层面，它们要通过WIFI通信的话，可以加载 wifi usb dougle。 

软件层面上，PI 和 NK1都是基于linux 系统，可以用各自的库函数可以 和 IO接口通信或者 UART 通信，和IO接口通信的目的就可以控制 小车的驱动板（I2C 或者 UART）的马达或是从传感器获取数据。（如果控制板和驱动板直接通过IO口相连的话）

从操作系统层面，未来要实现自动化小车，一个更标准的方案就是用ROS。ROS都可以安装到 PI 或者 NK1上面，要自定义实现，这个实现实际上就是上面软件层面的实现包装在ROS里面罢了。
1. 驱动层 / microcontroller  
   一般是指microcontroller上做马达的控制，传感器接受，同时只从控制板的接口接受命令。
   microcontroller 一般可以用 nodemcu， arduino 等等， 也可以直接连接小车的 集成的microcontroller板

建议一开始上手，控制板可以直接用 PI；
使用 linux；
获取图像数据；
控制IO口，发送UART；
MQTT建立和服务器通讯； 

NK1等到下一个阶段用到深度学习的时候再用。

**Comment by helxsz** [comment]
@shangwenxiang 通过 RX/TX 给控制板发送命令，后面是不是考虑在PI上面放着ROS， 摄像头采集数据，远程通过服务器控制PI， PI 和 控制板 通过RX/TX 直接连接？

**Comment by shangwenxiang** [comment]
目前考虑arduino和PI之间使用蓝牙串口进行通信，直接相互连接有烧坏PI板卡的可能性，使用蓝牙也是为了后期使用TK1替换PI的，使用蓝牙进行连接，可以分离上下层，下层车辆与上层控制分离

**Comment by shangwenxiang** [comment]
@helxsz PI上安装ROS，并且挂载摄像头，PI连接远程服务器，由远程服务器来发送控制指令给PI，PI同时将视频传送给远程服务器

**Comment by shangwenxiang** [comment]
@helxsz 关于方案2和方案3和方案4，意思应该就是PI板卡直接连接电机驱动板卡了，这时候应该就不需要arduino控制板了，PI的端口可以直接控制电机的运动了
