### ISSUE TITLE
树莓派问题

### ISSUE THREAD

**Issue by cuimiao187561** [GNSS523/ai_car_embedded#3]
树莓派3 HDMI 转VGA线在PHLIPS显示器出现彩屏，该如何解决？

**Comment by helxsz** [comment]
先检查是不是线和转换口的问题，然后再看系统，一般认为是硬件的问题。
不过这是小事。

**Comment by helxsz** [comment]
到论坛上去问，  http://www.shumeipai.net/forum.php， https://www.raspberrypi.org/forums/， http://bbs.elecfans.com/zhuti_shumeipai_1.html

**Comment by shangwenxiang** [comment]
@helxsz 已经解决，崔淼没有装好驱动，装好驱动就可以

**Comment by cuimiao187561** [comment]
@helxsz 师哥已经解决了，

**Comment by cuimiao187561** [comment]
_

- [ ] #1. 

_
