### ISSUE TITLE
导入lmdb库所遇到的问题

### ISSUE THREAD

**Issue by sifengyang** [GNSS523/ai_car_embedded#6]
当需要import lmdb时，如果遇到
![screenshot from 2016-12-30 20 32 28](https://cloud.githubusercontent.com/assets/22024525/21565140/28616ee0-cecf-11e6-9497-88a153e185f0.png)需要安装lmdb库。

**Comment by sifengyang** [comment]
使用sudo pip install lmdb,遇到import ××××出现问题统一使用pip install 安装

**Comment by helxsz** [comment]
@sifengyang imdb 是基本上deep learning 通用的存储数据的库，pip 也是常用安装 python库的类
